modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/boatload/issues"
license = "https://github.com/team-abnormals/boatload/blob/main/LICENSE.txt"

[[mods]]
    modId = "boatload"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "boatload:birch_furnace_boat"
    configBackground = "minecraft:textures/block/birch_planks.png"
    authors = "Team Abnormals"
    credits = "Markus1002, bageldotjpg"
    displayURL = "https://www.teamabnormals.com/mods/boatload"
    displayName = "Boatload"
    description = '''
    Adds some new kinds of boats to make ocean exploration more interesting.
    '''

[[dependencies.boatload]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.boatload]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.0.18,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.boatload]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.2.3,)"
    ordering = "AFTER"
    side = "BOTH"