modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/extra-boats/issues"
license = "https://github.com/team-abnormals/extra-boats/blob/main/LICENSE.txt"

[[mods]]
    modId = "extraboats"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "extraboats:birch_furnace_boat"
    configBackground = "minecraft:textures/block/birch_planks.png"
    authors = "Team Abnormals"
    credits = "Markus1002"
    displayURL = "https://www.teamabnormals.com/mods/extra-boats"
    displayName = "Extra Boats"
    description = '''
    Adds some new kinds of boats to make ocean exploration more interesting.
    '''

[[dependencies.extraboats]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.extraboats]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.2.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.extraboats]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.2.0,)"
    ordering = "AFTER"
    side = "BOTH"