modLoader="javafml"
loaderVersion="[29,)"
issueTrackerURL="https://github.com/Markus1002/Extra-Boats/issues"
[[mods]]
modId="extraboats"
version="1.3.5"
displayName="Extra Boats"
displayURL="https://www.curseforge.com/minecraft/mc-mods/extra-boats"
logoFile="logo.png"
credits="Markus1002, Translators: asthyr, Pandory_, kubajzzz, rio192al, kemiuu, peehpeh, F4zzer"
authors="Markus1002"
description='''Adds some new types of boats to make ocean exploration more interesting.'''
[[dependencies.extraboats]]
    modId="forge"
    mandatory=true
    versionRange="[29,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extraboats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
